### ISSUE TITLE
Change to border option breaks re-runs

### ISSUE THREAD

**Issue by kreynolds** [jeremyevans/sequel-annotate#10]
One of the reasons the border was inserted as the [second item here](https://github.com/jeremyevans/sequel-annotate/commit/896994c302011c654e24262c98997f2a731f2018#diff-c4c61d130617484227efa7152fc3e1abL215) is that it changes the comment detection and will add multiple comments on subsequent runs. If you want the border at the top, you'll need to [change how this works](https://github.com/jeremyevans/sequel-annotate/blob/master/lib/sequel/annotate.rb#L43).

**Comment by jeremyevans** [comment]
Sorry about that.  I figured it out and and fixed it locally a few days ago, but forgot to push the commit.  I just pushed the commit (2be93ec38380d415613fe49109ad6b7fb03bdc0d), so this is now fixed.

The previous insertion of the border after the second line resulted in inconsistent behavior because in the case where the table has a composite primary key, it puts the border between the primary key line and the columns line instead of after the columns line.
