### ISSUE TITLE
Annotation not working correctly with class_table_inheritance

### ISSUE THREAD

**Issue by bilby91** [jeremyevans/sequel-annotate#19]
Hello,

Today I implemented the sequel-annotate in one of my projects and I noticed that when using `class_table_inheritance`, subclasses table_name annotation is using the parent class always. 

In my case I have three model, `User`, `PersonUser` and `SystemUser`. The latter two inherit from `User`. On the annotated models, the three of them are showing this at the top. I would expect each class to reference it's own table.

```
# Table: users
```

The columns of the table seem to be inferred correctly.

**Comment by jeremyevans** [comment]
sequel-annotate does not currently support the class_table_inheritance plugin.  The described behavior doesn't sound wrong, since users would be the first table for each of the models.  For SystemUser and PersonUser, the users table is first, probably followed by system_users and person_users, respectively. 

I don't have plans to improve support in this area, but I'll definitely consider a pull request that recognizes when a class uses class_table_inheritance and documents the tables separately.
